### ISSUE TITLE
Collect list of ontology efforts

### ISSUE THREAD

**Issue by rartino** [Materials-Consortia/ontology#6]
@ml-evs sent us this link in the meeting Oct 30, 2020: https://pages.nist.gov/material-schema/

In the meeting before that we said to collect a list of all ontology efforts relevant for our effort.

(And this is the issue to remind us to do that)

**Comment by ml-evs** [comment]
Should have refreshed before posting my issue #7, I'll repost here and close it.

---

As mentioned at the end of the last meeting, there was some interest in collecting similar ontology efforts. There are two existing relevant compilations that I am aware of:

    The standardization section of @blokhin's awesome-materials-informatics list: https://github.com/tilde-lab/awesome-materials-informatics#standardization-initiatives
    A new awesome-chemical-data list I have been helping to curate, which has more of a focus on capturing experimental data/workflows: https://github.com/neo-chem/awesome-chemical-data#schemasontologies It does however contain the MGI schema I mentioned in the meeting https://github.com/usnistgov/mgi-json-schema, which is designed for schema.org

Both lists also contain links to further compilations...

**Comment by CasperWA** [comment]
I have created a wiki page in this repository for this list: https://github.com/Materials-Consortia/ontology/wiki/List-of-ontology-efforts
Perhaps we continue adding efforts there and close this issue? Or we keep the issue open and clearly direct to the wiki page? Or maybe the best would be to close this issue _when_ a clear link to the wiki page has been added to the README?
